name: Simple CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Verify index.html
      run: |
        if [ ! -f index.html ]; then
          echo " index.html is missing!"
          exit 1
        else
          echo " index.html found!"
        fi
