name: CI/CD Docker Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

test:
  runs-on: self-hosted
  needs: build
  steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Remove old container if exists
      run: docker rm -f test-container || true

    - name: Run container
      run: docker run --name test-container -d -p 8080:80 myapp:latest

    - name: Wait and Test container
      run: |
        sleep 5
        STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080 || true)
        echo "Status code: $STATUS"
        test "$STATUS" = "200"

    - name: Stop and remove container
      if: always()
      run: docker rm -f test-container || true






deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Deploy Docker container
        run: |
          docker rm -f myapp || true
          docker run -d --name myapp -p 80:80 myapp:latest
