name: CI/CD Docker Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Test Docker container
        run: |
          docker run --name test-container -d -p 8080:80 myapp:latest
          sleep 5
          curl -f http://localhost:8080/index.html | grep "Hello from Docker CI/CD"
          docker rm -f test-container

  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Deploy Docker container
        run: |
          docker rm -f myapp || true
          docker run -d --name myapp -p 80:80 myapp:latest
